clear; close all; clc;
load('Theta1.mat');
load('Theta2.mat');
X = loadMNISTImages('t10k-images.idx3-ubyte');
X = X';
y = loadMNISTLabels('t10k-labels.idx1-ubyte');
temp = y == 0;
y(temp) = 10;
pred = predict(Theta1, Theta2, X);
fprintf('Test Set Accuracy: %f\n', mean(double(pred == y)) * 100);